import { User, Service, Promotion, Role, PromotionStatus, InventoryItem } from './types';

// Default users
export const USERS: User[] = [
  { id: 'user-product', name: 'Team Product', role: Role.Product, username: 'product', password: '1' },
  { id: 'user-mkt', name: 'Team Marketing', role: Role.Marketing, username: 'mkt', password: '1' },
  { id: 'user-boss', name: 'Julie Nguyễn', role: Role.Management, username: 'admin', password: '1' },
  { id: 'user-reception', name: 'Lễ Tân', role: Role.Reception, username: 'reception', password: '1' },
  { id: 'user-accountant', name: 'Kế Toán', role: Role.Accountant, username: 'ketoan', password: '1' },
];

// Helper to create mock pricing
const createService = (id: string, name: string, category: string, desc: string, basePrice: number, discountPercent: number = 0, note: string = '', type: 'single' | 'combo' = 'single'): Service => {
    const pricePromo = discountPercent > 0 
        ? basePrice * (1 - discountPercent / 100)
        : Math.round(basePrice * 0.5 / 1000) * 1000;

    return {
        id,
        name,
        category,
        description: desc,
        type,
        consultationNote: note,
        priceOriginal: basePrice,
        discountPercent: discountPercent,
        pricePromo: pricePromo, 
        pricePackage5: basePrice * 5,
        pricePackage15: basePrice * 10,
        pricePackage3: basePrice * 3 * 0.95,
        pricePackage5Sessions: basePrice * 5 * 0.9, 
        pricePackage10: basePrice * 10 * 0.85, 
        pricePackage20: basePrice * 20 * 0.8, 
    };
};

export const SERVICES: Service[] = [
  createService('combo-rf-h-classic', 'RF + Hydrafacial (classic)', 'Combo Đặc Biệt', '', 6500000, 60, '', 'combo'),
  createService('combo-rf-h-sysnature', 'RF + Hydrafacial (sysnature)', 'Combo Đặc Biệt', '', 7600000, 60, '', 'combo'),
  createService('combo-rf-h-platinum', 'RF + Hydrafacial (platinum)', 'Combo Đặc Biệt', '', 9600000, 60, '', 'combo'),
  createService('rf-mat-matnong', 'RF mặt - mắt/nọng', 'Công nghệ RF', 'Thời lượng 30 phút', 4500000, 50),
  createService('rf-c+', 'C+', 'Công nghệ RF', '15 phút', 900000, 50),
  createService('rf-add-vitamin', 'Add Vitamin', 'Công nghệ RF', '15 phút', 900000, 50),
  createService('rf-mat', 'Mặt', 'Công nghệ RF', '30 phút', 3900000, 50),
  createService('rf-nong', 'Nọng', 'Công nghệ RF', '15 phút', 1800000, 50),
  createService('rf-mat-2', 'Mắt', 'Công nghệ RF', '10 phút', 1500000, 50),
  createService('rf-bap-tay', 'Bắp tay', 'Công nghệ RF', '30 phút', 2500000, 50),
  createService('rf-dui', 'Đùi', 'Công nghệ RF', '40 phút', 3000000, 50),
  createService('rf-bap-chuoi', 'Bắp chuối', 'Công nghệ RF', '30 phút', 3000000, 50),
  createService('rf-bung', 'Bụng', 'Công nghệ RF', '30 phút', 3500000, 50),
  createService('rf-that-lung-eo', 'Thắt lưng + Eo', 'Công nghệ RF', '30 phút', 3000000, 50),
  createService('hf-classic', 'Classic', 'Hydrafacial', '90 phút', 4600000, 60),
  createService('hf-sysnature', 'Sysnature', 'Hydrafacial', '105 phút', 5600000, 60),
  createService('hf-platinum', 'Platinum', 'Hydrafacial', '120 phút', 8900000, 60),
  createService('hf-body-lung', 'Body lưng', 'Hydrafacial', '45 phút', 5800000, 60),
  createService('hf-body-nguc', 'Body ngực', 'Hydrafacial', '45 phút', 5000000, 60),
  createService('hf-3-vung-body', '3 vùng body', 'Hydrafacial', '90 phút', 8000000, 60),
  createService('geneo-rf', 'KO RF', 'GeneoX Pro', '60 phút', 4500000, 50),
  createService('geneo-acid-neck', 'Acid Neck', 'GeneoX Pro', '30 phút', 1200000, 50),
  createService('hr-1', 'Mép trên', 'Triệt Lông', 'Triệt lông vùng mép trên', 750000, 30, '1. Cạo lông\n2. Bôi Gel lạnh\n3. Bắn laser\n4. Dưỡng da'),
  createService('hr-2', 'Nách/Trán/Cằm', 'Triệt Lông', 'Triệt lông vùng nách, trán, hoặc cằm', 950000, 30),
  createService('hr-3', '1/2 Tay', 'Triệt Lông', 'Triệt lông 1/2 cánh tay', 1200000, 30),
  createService('hr-4', '1/2 Chân', 'Triệt Lông', 'Triệt lông 1/2 chân', 1500000, 30),
  createService('hr-5', 'Toàn mặt', 'Triệt Lông', 'Triệt lông toàn bộ mặt', 1800000, 30),
  createService('hr-6', 'Ngực/Bụng', 'Triệt Lông', 'Triệt lông vùng ngực hoặc bụng', 1800000, 30),
  createService('hr-7', 'Full tay', 'Triệt Lông', 'Triệt lông toàn bộ cánh tay', 1800000, 30),
  createService('hr-8', 'Full chân', 'Triệt Lông', 'Triệt lông toàn bộ chân', 2000000, 30),
  createService('hr-9', 'Bikini/Tạo hình', 'Triệt Lông', 'Triệt lông và tạo hình vùng bikini', 1800000, 30),
  createService('hr-10', 'Lưng', 'Triệt Lông', 'Triệt lông vùng lưng', 2400000, 30),
  createService('hr-11', 'Tay + Chân + Nách', 'Combo Triệt Lông', 'Combo triệt lông tay, chân, và nách', 4200000, 30, '', 'combo'),
  createService('hr-12', 'Tay + Chân + Mặt', 'Combo Triệt Lông', 'Combo triệt lông tay, chân, và mặt', 4800000, 30, '', 'combo'),
  createService('hr-13', 'Tay + Chân + Bi', 'Combo Triệt Lông', 'Combo triệt lông tay, chân, và bikini', 4800000, 30, '', 'combo'),
  createService('hr-14', 'Toàn thân', 'Combo Triệt Lông', 'Triệt lông toàn thân', 9600000, 30, '', 'combo'),
  createService('service-old-3', 'Crystal Skin Therapy', 'Chăm sóc da', 'Thanh lọc – tái tạo – cấp ẩm đa tầng', 2500000, 64),
  createService('service-old-4', 'Bliss & Balance 105’', 'Thư giãn', '45’ Relaxing Hair Wash + 60 JU Signature Massage', 800000, 19),
  createService('service-old-5', 'Oxy Boots', 'Chăm sóc da', 'Công nghệ bơm oxy áp lực cao', 1800000, 11),
];

// NEW: Data Digitized from Menu Images
export const SPA_SERVICES_DATA: Partial<Service>[] = [
    // NAILS
    { name: 'Sơn Gel Cơ Bản', category: 'Nails', type: 'single', priceOriginal: 220000 },
    { name: 'Sơn Gel Hàn Cao Cấp', category: 'Nails', type: 'single', priceOriginal: 320000 },
    { name: 'Úp Móng Gel', category: 'Nails', type: 'single', priceOriginal: 250000 },
    { name: 'Thiết Kế Theo Yêu Cầu', category: 'Nails', type: 'single', priceOriginal: 15000, description: 'Giá từ 15k' },
    
    // LÔNG MI & MÀY
    { name: 'Nối Mi Tự Nhiên Classic', category: 'Lông Mi & Mày', type: 'single', priceOriginal: 400000 },
    { name: 'Nối Mi Volume', category: 'Lông Mi & Mày', type: 'single', priceOriginal: 650000 },
    { name: 'Uốn & Nhuộm Mi', category: 'Lông Mi & Mày', type: 'single', priceOriginal: 420000 },
    { name: 'Định Hình Chân Mày', category: 'Lông Mi & Mày', type: 'single', priceOriginal: 500000 },

    // MẸ & BÉ
    { name: 'Massage Mẹ Bầu', category: 'Mẹ & Bé', type: 'spa', price60: 760000, price90: 1100000 },
    { name: 'Massage Cho Bé', category: 'Mẹ & Bé', type: 'spa', price30: 250000, price60: 400000 },
    { name: 'Gội Đầu Cho Bé', category: 'Mẹ & Bé', type: 'spa', priceOriginal: 150000 },
    { name: 'Chăm Sóc Móng Cho Bé', category: 'Mẹ & Bé', type: 'spa', priceOriginal: 100000 },

    // CHĂM SÓC CƠ THỂ
    { name: 'Tắm Tẩy Tế Bào Chết Dịu Nhẹ', category: 'Chăm Sóc Cơ Thể', type: 'spa', price30: 480000 },
    { name: 'Tắm Dưỡng Mịn Da', category: 'Chăm Sóc Cơ Thể', type: 'spa', price60: 1600000 },
    { name: 'Tắm Dưỡng Sáng Da', category: 'Chăm Sóc Cơ Thể', type: 'spa', price60: 2500000 },

    // CHĂM SÓC TÓC
    { name: 'Gội Thư Giãn (45p)', category: 'Chăm Sóc Tóc', type: 'spa', priceOriginal: 250000 },
    { name: 'Gội Thảo Mộc Cao Cấp', category: 'Chăm Sóc Tóc', type: 'spa', price60: 600000, priceOriginal: 1080000, description: 'Giá 1080k cho 75 phút' },
    { name: 'Detox Da Đầu/Trị Gàu', category: 'Chăm Sóc Tóc', type: 'spa', price60: 500000 },
    { name: 'Tăng Sinh Mầm Tóc & Phục Hồi', category: 'Chăm Sóc Tóc', type: 'spa', price60: 600000 },

    // CHĂM SÓC DA MẶT
    { name: 'Dưỡng Da Cấp Ẩm Nhanh', category: 'Chăm Sóc Da Mặt', type: 'spa', price30: 380000 },
    { name: 'Phục Hồi Thải Độc Da', category: 'Chăm Sóc Da Mặt', type: 'spa', price60: 900000 },
    { name: 'Rạng Rỡ Xuân Thì', category: 'Chăm Sóc Da Mặt', type: 'spa', price60: 1200000 },
    { name: 'Sạch Mụn Mờ Thâm', category: 'Chăm Sóc Da Mặt', type: 'spa', price90: 1500000 },
    { name: 'Liệu Pháp Oxygen', category: 'Chăm Sóc Da Mặt', type: 'spa', price90: 1800000 },
    { name: 'Thanh Xuân Còn Mãi', category: 'Chăm Sóc Da Mặt', type: 'spa', price90: 2000000 },
    { name: 'Da Pha Lê', category: 'Chăm Sóc Da Mặt', type: 'spa', price90: 2500000 },
    { name: 'Liệu Pháp Bọt Oxy Nội Sinh Geneox Pro', category: 'Chăm Sóc Da Mặt', type: 'spa', price60: 3500000 },
    { name: 'RF Trẻ Hoá Và Săn Chắc Da Mặt', category: 'Chăm Sóc Da Mặt', type: 'spa', price60: 3900000 },
    { name: 'Hydrafacial Syndeo', category: 'Chăm Sóc Da Mặt', type: 'spa', price60: 4600000 },

    // MASSAGE
    { name: 'Liệu Pháp Tinh Dầu Aroma', category: 'Massage', type: 'spa', price60: 500000, price90: 710000, price120: 880000 },
    { name: 'Massage Thảo Mộc', category: 'Massage', type: 'spa', price60: 500000, price90: 710000, price120: 880000 },
    { name: 'Ju Signature', category: 'Massage', type: 'spa', price60: 550000, price90: 760000, price120: 980000 },
    { name: 'Massage Đá Nóng', category: 'Massage', type: 'spa', price60: 600000, price90: 850000, price120: 1080000 },
    { name: 'Thai/Shiatsu', category: 'Massage', type: 'spa', price60: 650000, price90: 920000, price120: 1200000 },
    { name: 'Chuyên Sâu Cổ-Vai-Gáy', category: 'Massage', type: 'spa', price30: 380000, price60: 600000, price90: 800000, price120: 1000000 },
    { name: 'Cân Bằng Hệ Bạch Huyết', category: 'Massage', type: 'spa', price60: 760000, price90: 1100000, price120: 1400000 },
    { name: 'Massage Đôi', category: 'Massage', type: 'spa', price60: 950000, price90: 1400000, price120: 1800000 },

    // CHĂM SÓC CHÂN
    { name: 'Gót Hồng', category: 'Chăm Sóc Chân', type: 'spa', price30: 300000 },
    { name: 'Tẩy Tế Bào Chết Cho Chân', category: 'Chăm Sóc Chân', type: 'spa', price30: 350000 },
    { name: 'Massage Ấn Huyệt', category: 'Chăm Sóc Chân', type: 'spa', price30: 280000, price60: 450000, price90: 600000, price120: 800000 },
    { name: 'Foot Pamper (45p)', category: 'Chăm Sóc Chân', type: 'spa', priceOriginal: 530000 },
    { name: 'Combo Pedicure (75p)', category: 'Chăm Sóc Chân', type: 'spa', priceOriginal: 620000 },
    { name: 'Total Foot Care (105p)', category: 'Chăm Sóc Chân', type: 'spa', priceOriginal: 750000 },
];

export const PROMOTIONS: Promotion[] = [
  {
    id: 'promo-1',
    name: 'Flash Sale Tháng 12',
    startDate: '2025-11-25',
    endDate: '2025-12-15',
    status: PromotionStatus.Approved,
    proposerId: 'user-product',
    designUrl: 'https://picsum.photos/1080/1920',
    salesNotes: "Chương trình sale cuối năm để kích cầu.",
    marketingNotes: "Design theo tone hồng chủ đạo, nhẹ nhàng.",
    services: [
      { ...SERVICES[26], fullPrice: SERVICES[26].priceOriginal, discountPrice: 2250000 },
      { ...SERVICES[27], fullPrice: SERVICES[27].priceOriginal, discountPrice: 1950000 },
      { ...SERVICES[28], fullPrice: SERVICES[28].priceOriginal, discountPrice: 899000 },
    ]
  },
  {
    id: 'promo-2',
    name: 'Đón Hè Rạng Rỡ',
    startDate: '2025-06-01',
    endDate: '2025-06-30',
    status: PromotionStatus.PendingDesign,
    proposerId: 'user-product',
    salesNotes: "Tập trung vào các dịch vụ làm sáng da và thư giãn.",
    services: [
      { ...SERVICES[26], fullPrice: SERVICES[26].priceOriginal, discountPrice: 3500000 },
      { ...SERVICES[28], fullPrice: SERVICES[28].priceOriginal, discountPrice: 2000000 },
    ]
  },
  {
    id: 'promo-3',
    name: 'Tri Ân Phái Đẹp',
    startDate: '2025-10-10',
    endDate: '2025-10-20',
    status: PromotionStatus.PendingApproval,
    proposerId: 'user-product',
    designUrl: 'https://picsum.photos/1080/1920',
    salesNotes: "Chương trình cho ngày 20/10.",
    marketingNotes: "Thiết kế đã xong, chờ sếp duyệt.",
    services: [
       { ...SERVICES[30], fullPrice: SERVICES[30].priceOriginal, discountPrice: 1500000 },
    ]
  }
];

// Helper to create Inventory Item safely without undefined values
const inv = (name: string, location: string, unit: string, qty: number, expiry?: string): InventoryItem => {
    const item: any = {
        id: `inv-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        name, 
        location, 
        unit, 
        quantity: qty
    };
    if (expiry) {
        item.expiryDate = expiry;
    }
    return item as InventoryItem;
};

// INITIAL INVENTORY DATA
export const INVENTORY_ITEMS: InventoryItem[] = [
    // KỆ A
    inv('Giấy vệ sinh nhân viên', 'KỆ A', 'cây', 4),
    inv('Giấy vệ sinh cho khách', 'KỆ A', 'cây', 21),
    inv('Viên xả bồn cầu', 'KỆ A', 'cái', 1),
    inv('Ly giấy', 'KỆ A', 'cây', 3),
    inv('Nước giặt xả lớn Max Kleen', 'KỆ A', 'bịch', 5),
    inv('Nước lau kính', 'KỆ A', 'chai', 3),
    inv('Bột giặt Omo 5KG', 'KỆ A', 'gói', 1),
    inv('Đèn Leaf - bắt muỗi', 'KỆ A', 'cái', 1),
    inv('Đèn Nightlight', 'KỆ A', 'cái', 1),
    inv('Dép nhân viên cao', 'KỆ A', 'đôi', 5),
    
    // ... (Giữ nguyên các item cũ ở đây) ...
    inv('Găng tay cao su loại to', 'KỆ A', 'ĐÔI', 2),
    inv('Gel lọc sợi vải', 'KỆ A', 'bịch', 2),
    inv('Ky hốt rác', 'KỆ A', 'cái', 1),
    inv('Listerin', 'KỆ A', 'chai', 2),
    inv('Máy sấy Dyson', 'KỆ A', 'cái', 2),
    inv('Miếng lau nhà', 'KỆ A', 'cái', 17),
    inv('Nước lau sàn Max Kleen', 'KỆ A', 'bình', 3),
    inv('Nước lau sàn Max LỚN', 'KỆ A', 'gói', 4),
    inv('Nước lau sàn Max NHỎ', 'KỆ A', 'gói', 3),
    inv('Nước rửa tay 1 Aqua Vera', 'KỆ A', 'chai', 1),
    inv('Vim', 'KỆ A', 'chai', 2),
    inv('Cuộn lăn bụi', 'KỆ A', 'cái', 4),
    inv('Khăn giấy rút - Vuông Bless you', 'KỆ A', 'gói', 16),
    inv('Túi đựng rác', 'KỆ A', 'bịch', 10),
    inv('Long não 1KG', 'KỆ A', 'túi', 4),
    inv('Nến teelight', 'KỆ A', 'hộp', 3),
    
    // DỮ LIỆU MỚI NHẬP TỪ DANH SÁCH LỄ TÂN
    inv('Dầu gội Shine 750ml', 'LỄ TÂN', 'chai', 1),
    inv('Dầu xả Label Shine 750ml', 'LỄ TÂN', 'chai', 1),
    inv('Lotion Seobo Balance 1L', 'LỄ TÂN', 'chai', 1),
    inv('Cleansing Milk Seobo 1L', 'LỄ TÂN', 'chai', 1),
    inv('Oil Contras 5A2 400ml', 'LỄ TÂN', 'chai', 1),
    inv('Tinh dầu bưởi', 'LỄ TÂN', 'chai', 4),
    inv('Xịt dưỡng tóc bưởi Cafune', 'LỄ TÂN', 'chai', 1),
    inv('Dầu xả Aveda 1L', 'LỄ TÂN', 'chai', 2),
    inv('Dầu gội Aveda 1L', 'LỄ TÂN', 'chai', 1),
    inv('Dầu gội Velvet 850ml', 'LỄ TÂN', 'chai', 1),
    inv('Mặt nạ Clistech', 'LỄ TÂN', 'chai', 1),
    inv('Mặt nạ Clistech (miếng)', 'LỄ TÂN', 'miếng', 5),
    inv('Tinh dầu sả chanh 500ml', 'LỄ TÂN', 'chai', 1),
    inv('Dầu matxa toàn thân Sore Muscle', 'LỄ TÂN', 'chai', 1),
    inv('Dầu matxa toàn thân Relaxation', 'LỄ TÂN', 'chai', 1),
    inv('Tinh dầu bạc hà', 'LỄ TÂN', 'lọ', 1),
    inv('Tinh dầu Bạch Đàn Chanh', 'LỄ TÂN', 'lọ', 1),
    inv('Brown Herbal 25ml', 'LỄ TÂN', 'lọ', 1),
    inv('Tinh dầu cam ngọt 100ml', 'LỄ TÂN', 'lọ', 1),
    inv('Tinh dầu Ngọc Lan Tây', 'LỄ TÂN', 'lọ', 1),
    inv('Tinh dầu Trà xanh', 'LỄ TÂN', 'lọ', 1),
    inv('Tinh dầu hoa lài', 'LỄ TÂN', 'lọ', 1),
    inv('Tinh dầu Oải Hương 100ml', 'LỄ TÂN', 'lọ', 2),
    inv('Tinh dầu chanh sả', 'LỄ TÂN', 'lọ', 1),
    inv('Tinh dầu xá xị 50ml', 'LỄ TÂN', 'lọ', 1),
    inv('Tinh dầu Gỗ Melone', 'LỄ TÂN', 'lọ', 1),
    inv('Chai trị gàu 30ml Briogeo', 'LỄ TÂN', 'lọ', 2),
    inv('Forest Hair Midori', 'LỄ TÂN', 'chai', 1),
    inv('VP Start Moisturizing Cream', 'LỄ TÂN', 'hũ', 1),
    inv('Dầu xả Scalp pack Dr Forhair', 'LỄ TÂN', 'hộp', 1),
    inv('Sea Salt Dr Forhair', 'LỄ TÂN', 'ống', 1),
    inv('Dầu gội HARNN 250ml', 'LỄ TÂN', 'chai', 1),
    inv('Dầu xả HARNN 150ml', 'LỄ TÂN', 'chai', 1),
    inv('Mặt nạ HARNN', 'LỄ TÂN', 'hũ', 1),
    inv('Tẩy tế bào chết HARNN', 'LỄ TÂN', 'hũ', 1),
    inv('Dầu Matxa HARNN', 'LỄ TÂN', 'chai', 1),
    inv('Toner HARNN', 'LỄ TÂN', 'chai', 1),
    inv('Sữa rửa mặt HARNN', 'LỄ TÂN', 'tuýp', 1),
    inv('Nourishing Gel HARNN 55ml', 'LỄ TÂN', 'chai', 1),
    inv('Body oil Alqvimia (Queen of Egypt)', 'LỄ TÂN', 'chai', 4),
    inv('Body oil Alqvimia (Lavender)', 'LỄ TÂN', 'chai', 1),
    inv('Hũ màu hồng mini chiết mỹ phẩm', 'LỄ TÂN', 'hũ', 2),
    inv('Mỡ trăn Nstore', 'LỄ TÂN', 'hộp', 2),
    inv('Skin Conditioner Hatomugi', 'LỄ TÂN', 'chai', 2),
    inv('Kem ủ Biotin + Collagen', 'LỄ TÂN', 'hũ', 1),
    inv('Hand Lotion Rich', 'LỄ TÂN', 'chai 20ml', 1),
    inv('Chai tinh dầu Kathy', 'LỄ TÂN', 'chai', 1),
    inv('Sữa rửa mặt Pumpkin', 'LỄ TÂN', 'chai', 1),
    inv('Kem dưỡng SOS', 'LỄ TÂN', 'tuýp', 1),
    inv('Kem trắng Alpha 3 Arbutin', 'LỄ TÂN', 'chai', 1),
    inv('Serum Collagen Alpha 3', 'LỄ TÂN', 'chai', 1),
    inv('Thuốc kích trắng Alpha 3', 'LỄ TÂN', 'tuýp', 1),
    inv('Sữa rửa mặt SOS', 'LỄ TÂN', 'tuýp', 1),
    inv('Sữa rửa mặt HadaLabo 40gram', 'LỄ TÂN', 'tuýp', 1),
    inv('Kem chống nắng Ultimate', 'LỄ TÂN', 'lọ', 1),
    inv('Sữa rửa mặt Cocoon', 'LỄ TÂN', 'chai', 1),
    inv('Tẩy tế bào chết Cocoon', 'LỄ TÂN', 'chai', 1),
    inv('Dầu gội khô tóc Spes', 'LỄ TÂN', 'chai', 1),
    inv('Body Gel hot burning', 'LỄ TÂN', 'tuýp', 1),
    inv('Kem dưỡng Luca\'s Papaw', 'LỄ TÂN', 'tuýp', 2),
    inv('Sữa rửa mặt Caudalie 100ml', 'LỄ TÂN', 'lọ', 1),
    inv('Dầu cho bà bầu Tei Oil', 'LỄ TÂN', 'chai', 1),
    inv('Hũ Vasaline 250ml', 'LỄ TÂN', 'hũ', 1),
    inv('Kem dưỡng thể Hatomugi', 'LỄ TÂN', 'chai', 1),
    inv('Gel rửa tay Aqua Vera 500ml', 'LỄ TÂN', 'chai', 2),
    inv('Dầu Matxa Estherpo Jojoba', 'LỄ TÂN', 'chai', 1),
    inv('Dầu Matxa Estherpo Lavender', 'LỄ TÂN', 'chai', 1),
    inv('Dầu Matxa Estherpo Lemon soft', 'LỄ TÂN', 'chai', 1),
    inv('Essence for hair GFH 100ml', 'LỄ TÂN', 'hộp', 1),
    inv('Dầu matxa gừng', 'LỄ TÂN', 'chai', 2),
    inv('Matxa tay Rich hand', 'LỄ TÂN', 'chai', 1),
    inv('Nature Oil Kathy 100ml', 'LỄ TÂN', 'chai', 1),
    inv('Đèn cầy máy', 'LỄ TÂN', 'cái', 1),
    inv('Repair Skin care Raingrass', 'LỄ TÂN', 'hộp', 2),
    inv('Skin Start Skin Management Centre', 'LỄ TÂN', 'chai', 2),
    inv('Nước xịt dưỡng tóc bưởi Cafune', 'LỄ TÂN', 'chai', 2),
    inv('Dập nát mi Repair', 'LỄ TÂN', 'tuýp', 1),
    inv('Nước tẩy trang AO3', 'LỄ TÂN', 'chai', 1),
    inv('Nước tẩy trang AS1', 'LỄ TÂN', 'chai', 1),
    inv('Tinh dầu Himalaya 50ml', 'LỄ TÂN', 'lọ', 1),
    inv('DBH collagen', 'LỄ TÂN', 'chai', 1),
    inv('Botoxol', 'LỄ TÂN', 'lọ', 5),
    inv('Glycal Prep', 'LỄ TÂN', 'lọ', 5),
    inv('Mặt nạ Banabagi', 'LỄ TÂN', 'miếng', 5),
    inv('Mặt nạ Vitality Skin', 'LỄ TÂN', 'miếng', 6),
    inv('Mặt nạ đắp rãnh cười Seomou', 'LỄ TÂN', 'miếng', 9),
    inv('Mặt nạ mắt', 'LỄ TÂN', 'miếng', 14),
    inv('Dầu gội Dr Forhair', 'LỄ TÂN', 'túi mini', 5),
    inv('VP Start Nicotinamide', 'LỄ TÂN', 'lọ', 1),
    inv('DBH Phospholipid Cream', 'LỄ TÂN', 'hũ', 1),
    inv('DBH Cellular Hydration Masque', 'LỄ TÂN', 'hũ', 1),
    inv('DBH Vitamin C powder', 'LỄ TÂN', 'hũ', 1),
    inv('DBH Aloe Response Masque', 'LỄ TÂN', 'hũ', 1),
    inv('DBH Green Apple Fruit Peel', 'LỄ TÂN', 'hũ', 1),
    inv('Nano Needling Pen', 'LỄ TÂN', 'bộ', 1),
    inv('Linear Cartridge', 'LỄ TÂN', 'hộp', 1),
    inv('DBH DNA Matrix Serum', 'LỄ TÂN', 'lọ', 1),
    inv('DBH FO2 two gel', 'LỄ TÂN', 'chai', 1),
    inv('DBH FO2 one gel', 'LỄ TÂN', 'chai', 1),
    inv('DBH Aloe Essence', 'LỄ TÂN', 'chai', 1),
    inv('DBH Lactic 20 recovery blend', 'LỄ TÂN', 'lọ', 1),
    inv('DBH Pre Peel Cleanser', 'LỄ TÂN', 'chai', 1),
    inv('DBH O2 Hydra Mist', 'LỄ TÂN', 'chai', 1),
    inv('DBH Silk Milk Cream Cleaser', 'LỄ TÂN', 'chai', 1),
    inv('DBH Natur Jojoba Cleaning Bead Scrub', 'LỄ TÂN', 'chai', 1),
    inv('DBH Prepeel skin wash', 'LỄ TÂN', 'chai', 1),
    inv('DBH Salix Tone', 'LỄ TÂN', 'chai', 1),
    inv('DBH Amino Netralizer', 'LỄ TÂN', 'chai', 1),
    inv('DBH Ga 30 Exfoliator', 'LỄ TÂN', 'chai', 1),
    inv('DBH Green Premium Cleansing Oil', 'LỄ TÂN', 'chai', 1),
    inv('Body Oil Queen of Egypt', 'LỄ TÂN', 'hộp', 2),
    inv('Body Oil for Firm and Healthy', 'LỄ TÂN', 'hộp', 1),
    inv('Body Oil for Queen of Egypt Toilettes', 'LỄ TÂN', 'hộp', 1),
    inv('Body Oil Lavender Relaxing', 'LỄ TÂN', 'hộp', 1),
    inv('BNV Biolab 2.2ml', 'LỄ TÂN', 'lọ', 5),
    inv('Mặt nạ chân xanh dương', 'LỄ TÂN', 'miếng', 20),
    inv('Mặt nạ chân trắng', 'LỄ TÂN', 'miếng', 34),
    inv('Mặt nạ tay hồng', 'LỄ TÂN', 'miếng', 23),
    inv('Tuýp đầu hydrafacial xanh dương', 'LỄ TÂN', 'cái', 5),
    inv('Tuýp đầu hydrafacial xanh lá', 'LỄ TÂN', 'cái', 5),
    inv('Tuýp đầu hydrafacial trắng', 'LỄ TÂN', 'cái', 55),
    inv('Lamination - Lift Glue', 'LỄ TÂN', 'hộp', 3),
    inv('Lamination - Lift Lotion', 'LỄ TÂN', 'túi mini', 8),
    inv('Lamination - Neutralizer', 'LỄ TÂN', 'túi mini', 9),
    inv('Lamination - Lash Botox', 'LỄ TÂN', 'túi', 2),
    inv('Uốn mi - Treatment', 'LỄ TÂN', 'chai', 1),
    inv('Uốn và tint (túi mini)', 'LỄ TÂN', 'cặp', 11),
    inv('Tint', 'LỄ TÂN', 'túi mini', 3),
    inv('Dao cạo su màu đen', 'LỄ TÂN', 'cái', 2),
    inv('Lưới bọc rác', 'LỄ TÂN', 'cái', 54),
    inv('Miếng màu vàng không để hiệu', 'LỄ TÂN', 'miếng', 8),
    inv('Bột Màu tắm dưỡng', 'LỄ TÂN', 'hộp', 1),
    inv('Mặt nạ Body Sea Weed', 'LỄ TÂN', 'túi', 2),
    inv('Cánh hoa hồng khô', 'LỄ TÂN', 'túi', 1),
    inv('Muối than thảo mộc', 'LỄ TÂN', 'túi', 1),
    inv('Sáp Wax lông Glow', 'LỄ TÂN', 'bịch', 5),
    inv('Sáp Wax lông Hywaxing', 'LỄ TÂN', 'hũ', 5),
    inv('Máy đo nhiệt độ Bandan Originally', 'LỄ TÂN', 'cái', 2),
    inv('Tool box hộp xám', 'LỄ TÂN', 'hộp', 2),
    inv('Máy Hitachi', 'LỄ TÂN', 'cái', 1),
    inv('Nịt trái cây', 'LỄ TÂN', 'bịch', 1),
    inv('Collagen Lip Mash', 'LỄ TÂN', 'gói', 1),
    inv('Hộp dụng cụ dặm phấn', 'LỄ TÂN', 'cái', 1),
    inv('NWN White skin lotion', 'LỄ TÂN', 'chai', 2),
    inv('Babi Mild Bioganik', 'LỄ TÂN', 'chai', 2),
    inv('Lavender Fragrance', 'LỄ TÂN', 'hũ', 2),
    inv('Mặt nạ thải độc da Herbes', 'LỄ TÂN', 'hũ', 1),
    inv('Đồ makeup khách', 'LỄ TÂN', 'bộ', 1),
    inv('Miếng dán ti', 'LỄ TÂN', 'gói', 20),
    inv('Vitamin C Aloe Vera', 'LỄ TÂN', 'hộp', 1),
    inv('VP Start', 'LỄ TÂN', 'chai', 5),
    inv('Vitality Sheet Mask', 'LỄ TÂN', 'hộp', 1),
    inv('Máy duỗi tóc Dyson', 'LỄ TÂN', 'cái', 1),
    inv('Máy uốn tóc Nova', 'LỄ TÂN', 'cái', 1),
    inv('Quần lót giấy', 'LỄ TÂN', 'cái', 4),
    inv('Vớ xông hơi 2 cái', 'LỄ TÂN', 'kg', 1),
    inv('Dema Scalp intensive serum MBA', 'LỄ TÂN', 'hộp', 2),
    inv('Smoothy wash DDVS', 'LỄ TÂN', 'chai', 1),
    inv('Hộp đựng trang độc màu đỏ', 'LỄ TÂN', 'hộp', 8),
    inv('Tag gỗ', 'LỄ TÂN', 'cái', 11),
    inv('Estherpo Cool Smooth', 'LỄ TÂN', 'chai', 1),
    inv('Bã kẽ', 'LỄ TÂN', 'túi', 1),
    inv('Kềm vàng 86k', 'LỄ TÂN', 'cái', 1),
    inv('Kềm bạc nhỏ', 'LỄ TÂN', 'cái', 2),
    inv('Kềm bạc 175k', 'LỄ TÂN', 'cái', 2),
    inv('Vitamin C Skin Care 29.57ml', 'LỄ TÂN', 'lọ', 1),
    inv('Skinceutical Hydrating 15ml', 'LỄ TÂN', 'lọ', 1),
    inv('Bịch trà ngâm chân', 'LỄ TÂN', 'bịch', 1),
    inv('Trà thanh lọc', 'LỄ TÂN', 'hộp', 4),
    inv('Tăm bông', 'LỄ TÂN', 'hộp', 3),
    inv('Giấy in nail', 'LỄ TÂN', 'cuộn', 2),
    inv('Giấy dán date', 'LỄ TÂN', 'cuộn', 7),
    inv('Hộp kim bấm', 'LỄ TÂN', 'hộp', 13),
    inv('Miếng dán Siae S M', 'LỄ TÂN', 'bịch', 1),
    inv('Gel chà ghế da', 'LỄ TÂN', 'hũ', 1),
    inv('Loọ thủy tinh mài nứt bầu', 'LỄ TÂN', 'cái', 19),
    inv('Bath Bomb Herbal', 'LỄ TÂN', 'cái', 1),
    inv('Tinh dầu gừng Kamala', 'LỄ TÂN', 'lọ', 1),
    inv('Massa oil body 10ml', 'LỄ TÂN', 'lọ', 1),
    inv('Gel làm sáng da', 'LỄ TÂN', 'túi', 28),
    inv('Giấy A4', 'LỄ TÂN', 'ram', 3),
    inv('Giấy A5', 'LỄ TÂN', 'ram', 1),
    inv('Mặt nạ hút mụn đậu đen', 'LỄ TÂN', 'miếng', 1),
    inv('Hộp sữa tươi', 'LỄ TÂN', 'hộp', 28),
    inv('Locker đồng hồ màu hồng', 'LỄ TÂN', 'cái', 20),
    inv('Locker đồng hồ màu đen', 'LỄ TÂN', 'cái', 20),
    inv('Chai Hydrafacial - Antiox', 'LỄ TÂN', 'chai', 4),
    inv('Chai Hydrafacial - Activ 4', 'LỄ TÂN', 'chai', 1),
    inv('Rin seaway', 'LỄ TÂN', 'chai', 4),
    inv('Glysal Prep màu nâu', 'LỄ TÂN', 'lọ', 6),
    inv('Glysal Prep màu xám', 'LỄ TÂN', 'lọ', 1),
    inv('Thùng nước lọc cho khách', 'LỄ TÂN', 'thùng', 4),
    inv('Mặt nạ mắt Collagen', 'LỄ TÂN', 'gói', 4),
    inv('Mặt nạ môi', 'LỄ TÂN', 'gói', 5),
    inv('Ton dưỡng mi', 'LỄ TÂN', 'lọ', 4),
    inv('Serum dưỡng mi', 'LỄ TÂN', 'lọ', 4),
    inv('Gen hair Scalp 1', 'LỄ TÂN', 'chai', 2),
    inv('Gen Hair Scalp 2', 'LỄ TÂN', 'chai', 1),
    inv('Lọ chăm sóc chân mày mi', 'LỄ TÂN', 'lọ', 2),
];